version = 0.1
[default.deploy.parameters]
stack_name = "test-api-gateway"
resolve_s3 = true
s3_prefix = "test-api-gateway"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
