AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This CloudFormation template creates a DynamoDB table.
Parameters:
    TableName:
        Type: String
        Description: The name of the DynamoDB table
    Stage:
        Type: String
        Description: The name of the stage (e.g., development, production)

Resources:
    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Sub "${TableName}-${Stage}"
            AttributeDefinitions:
                - AttributeName: "PK"
                  AttributeType: "S"
                - AttributeName: "SK"
                  AttributeType: "S"
            KeySchema:
                - AttributeName: "PK"
                  KeyType: "HASH"
                - AttributeName: "SK"
                  KeyType: "RANGE"
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5

Outputs:
    DynamoDBTableName:
        Description: The name of the created DynamoDB table
        Value: !Ref DynamoDBTable
        Export:
            Name: !Sub "DynamoDBTable"
    DynamoDBTableArn:
        Description: The Amazon Resource Name (ARN) of the created DynamoDB table
        Value: !GetAtt DynamoDBTable.Arn
        Export:
            Name: !Sub "DynamoDBTableArn"
