AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AWS SAM Template for making API Gateway with APIGatewayRole for invoking
  lambda functions. Generate lambda functions according to docs\Visitor Management
  System Swagger 1.yaml

  '
Globals:
  Function:
    Timeout: 3
    Runtime: python3.11
    Environment:
      Variables:
        Environment:
          Ref: Environment
        BucketName:
          Ref: BucketName
        DynamoDBTableName:
          Ref: DynamoDBTable
  Api:
    Cors:
      AllowMethods: '''DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'''
      AllowHeaders: '''Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'''
      AllowOrigin: '''*'''
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
    Description: Environment name
  BucketName:
    Type: String
    Description: Name of the S3 bucket
  DynamoDBTable:
    Type: String
    Description: Name of the DynamoDB table
  UserPoolClientId:
    Type: String
    Description: User Pool Client ID
  UserPoolId:
    Type: String
    Description: User Pool ID
  LambdaIAMRoleArn:
    Type: String
    Description: ARN of the Lambda IAM Role
  CognitoPoolArn:
    Type: String
    Description: ARN of the Cognito Pool
  SenderMail:
    Type: String
    Description: Email of the sender
  ReceiverMail:
    Type: String
    Description: Email of the receiver
  JWTSecret:
    Type: String
    Description: JWT Secret
Resources:
  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${Environment}--ApiGatewayRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName:
          Fn::Sub: ${Environment}--ApiGatewayRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
            - Fn::GetAtt:
              - VMSLoginGET
              - Arn
            - Fn::GetAtt:
              - VMSVisitorGET
              - Arn
            - Fn::GetAtt:
              - VMSVisitorPOST
              - Arn
            - Fn::GetAtt:
              - VMSVisitorIdGET
              - Arn
            - Fn::GetAtt:
              - VMSVisitorIdPUT
              - Arn
            - Fn::GetAtt:
              - VMSVisitGET
              - Arn
            - Fn::GetAtt:
              - VMSVisitPOST
              - Arn
            - Fn::GetAtt:
              - VMSVisitIdGET
              - Arn
            - Fn::GetAtt:
              - VMSVisitIdPATCH
              - Arn
            - Fn::GetAtt:
              - VMSCardGET
              - Arn
            - Fn::GetAtt:
              - VMSCardPOST
              - Arn
            - Fn::GetAtt:
              - VMSCardIdGET
              - Arn
            - Fn::GetAtt:
              - VMSCardIdPUT
              - Arn
            - Fn::GetAtt:
              - VMSApprovalPOST
              - Arn
            - Fn::GetAtt:
              - VMSApprovalIdPATCH
              - Arn
            - Fn::GetAtt:
              - VMSApprovalIdGET
              - Arn
            - Fn::GetAtt:
              - VMSForgotPasswordPOST
              - Arn
    Metadata:
      SamResourceId: ApiGatewayRole
  VMSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: Environment
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://abhi-code-sam/3194a440ec302cd5b5faecadcbf9e9d1
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: '''*'''
              Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
              Access-Control-Allow-Methods: '''GET,OPTIONS,POST,PUT,DELETE'''
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: '''*'''
              Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
              Access-Control-Allow-Methods: '''GET,OPTIONS,POST,PUT,DELETE'''
    Metadata:
      SamResourceId: VMSApiGateway
  VMSLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-VMS-Layer
      Description: VMS Lambda Layer
      ContentUri: s3://abhi-code-sam/b9397f41e9c6ef9f679d2685e0af9ba7
      CompatibleRuntimes:
      - python3.11
    Metadata:
      SamResourceId: VMSLayer
  VMSLoginGET:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          UserPoolClientId:
            Ref: UserPoolClientId
          UserPoolId:
            Ref: UserPoolId
      FunctionName:
        Fn::Sub: ${Environment}-VMS-login-GET
      CodeUri: s3://abhi-code-sam/edf8184a2dec39ff8df93a306ec2c1c7
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSLoginGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /login/{proxy+}
            Method: post
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /login/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSLoginGET
  VMSForgotPasswordPOST:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          UserPoolClientId:
            Ref: UserPoolClientId
          UserPoolId:
            Ref: UserPoolId
      FunctionName:
        Fn::Sub: ${Environment}-VMS-forgot-password-POST
      CodeUri: s3://abhi-code-sam/77f8fe131fa9e4e59c2304ab651501b8
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSForgotPasswordPOST:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /forgot_password/{proxy+}
            Method: post
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /forgot_password/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSForgotPasswordPOST
  VMSVisitorGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visitor-GET
      CodeUri: s3://abhi-code-sam/a376e42d2d56e982655abf9dcdb42381
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSVisitorGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visitor/{proxy+}
            Method: get
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visitor/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitorGET
  VMSVisitorPOST:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visitor-POST
      CodeUri: s3://abhi-code-sam/9dd6c7bac0e0b96023419c71bf8af960
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Role:
        Ref: LambdaIAMRoleArn
      Events:
        VMSVisitorPOST:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visitor/{proxy+}
            Method: post
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visitor/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitorPOST
  VMSVisitorIdGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visitor-id-GET
      CodeUri: s3://abhi-code-sam/d2a5431b8f450322d874ea025168e539
      Handler: app.lambda_handler
      Runtime: python3.11
      Role:
        Ref: LambdaIAMRoleArn
      Layers:
      - Ref: VMSLayer
      Events:
        VMSVisitorVisitorIdGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visitor/{id}/{proxy+}
            Method: get
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visitor/{id}/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitorIdGET
  VMSVisitorIdPUT:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visitor-id-PUT
      CodeUri: s3://abhi-code-sam/35bf07687916bfcde02f0b66c43a17bc
      Handler: app.lambda_handler
      Runtime: python3.11
      Role:
        Ref: LambdaIAMRoleArn
      Layers:
      - Ref: VMSLayer
      Events:
        VMSVisitorVisitorIdPUT:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visitor/{id}/{proxy+}
            Method: put
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitorIdPUT
  VMSVisitGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visit-GET
      CodeUri: s3://abhi-code-sam/d16b937791f526e6792c84e9aed617b7
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSVisitGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visit/{proxy+}
            Method: get
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visit/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitGET
  VMSVisitPOST:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visit-POST
      CodeUri: s3://abhi-code-sam/4a2f5fc6b5ccb416a96a5a1d996e11d3
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSVisitPOST:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visit/{proxy+}
            Method: post
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visit/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitPOST
  VMSVisitIdGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visit-id-GET
      CodeUri: s3://abhi-code-sam/acf2d3d5960e4985e41c047f14acb6ac
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSVisitVisitIdGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visit/{id}/{proxy+}
            Method: get
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visit/{id}/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitIdGET
  VMSVisitIdPATCH:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visit-id-PATCH
      CodeUri: s3://abhi-code-sam/c66f8b4fd901696639da0573d90c8dff
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSVisitVisitIdPATCH:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visit/{id}/{proxy+}
            Method: patch
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visit/{id}/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitIdPATCH
  VMSCardGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-card-GET
      CodeUri: s3://abhi-code-sam/2b975e9a74772cd7b6f8de68b4f46e29
      Handler: app.lambda_handler
      Runtime: python3.11
      Role:
        Ref: LambdaIAMRoleArn
      Layers:
      - Ref: VMSLayer
      Events:
        VMSCardGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /card/{proxy+}
            Method: get
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /card/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSCardGET
  VMSCardPOST:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-card-POST
      CodeUri: s3://abhi-code-sam/9d4f04710f35cce41307979533a9e892
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSCardPOST:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /card/{proxy+}
            Method: post
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /card/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSCardPOST
  VMSCardIdGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-card-id-GET
      CodeUri: s3://abhi-code-sam/a469a84ae87875072afb80f7f3248aa4
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSCardCardIdGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /card/{id}/{proxy+}
            Method: get
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /card/{id}/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSCardIdGET
  VMSCardIdPUT:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-card-id-PUT
      CodeUri: s3://abhi-code-sam/d7f5b7718fcfe0516b8454232020452a
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSCardCardIdPUT:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /card/{id}/{proxy+}
            Method: put
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /card/{id}/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSCardIdPUT
  VMSApprovalPOST:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-approval-POST
      CodeUri: s3://abhi-code-sam/65f02af2388ed9207ad05145fdc74832
      Handler: app.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          SENDER_EMAIL:
            Ref: SenderMail
          RECIPIENT_EMAIL:
            Ref: ReceiverMail
          JWT_SECRET:
            Ref: JWTSecret
      Layers:
      - Ref: VMSLayer
      Events:
        VMSApprovalPOST:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /approval/{proxy+}
            Method: post
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /approval/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
      Role:
        Ref: LambdaIAMRoleArn
    Metadata:
      SamResourceId: VMSApprovalPOST
  VMSApprovalIdGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-approval-id-GET
      CodeUri: s3://abhi-code-sam/b7786680ce36fa253e75c5ff30d6e2c2
      Handler: app.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          JWT_SECRET:
            Ref: JWTSecret
      Layers:
      - Ref: VMSLayer
      Events:
        VMSApprovalApprovalIdGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /approval/{id}/{proxy+}
            Method: get
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /approval/{id}/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSApprovalIdGET
  VMSApprovalIdPATCH:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-approval-id-PATCH
      CodeUri: s3://abhi-code-sam/e6891d434149e6bb1d882f979a632716
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSApprovalApprovalIdPATCH:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /approval/{id}/{proxy+}
            Method: patch
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /approval/{id}/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSApprovalIdPATCH
Outputs:
  VMSApiEndpoint:
    Description: VMS API Gateway endpoint URL
    Value:
      Fn::Sub: https://${VMSApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
