AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AWS SAM Template for making API Gateway with APIGatewayRole for invoking
  lambda functions. Generate lambda functions according to docs\Visitor Management
  System Swagger 1.yaml

  '
Globals:
  Function:
    Timeout: 3
    Runtime: python3.11
    Environment:
      Variables:
        Environment:
          Ref: Environment
        BucketName:
          Ref: BucketName
        DynamoDBTableName:
          Ref: DynamoDBTable
  Api:
    Cors:
      AllowMethods: '''DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'''
      AllowHeaders: '''Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'''
      AllowOrigin: '''*'''
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
    Description: Environment name
  BucketName:
    Type: String
    Description: Name of the S3 bucket
  DynamoDBTable:
    Type: String
    Description: Name of the DynamoDB table
  UserPoolClientId:
    Type: String
    Description: User Pool Client ID
  UserPoolId:
    Type: String
    Description: User Pool ID
  LambdaIAMRoleArn:
    Type: String
    Description: ARN of the Lambda IAM Role
  CognitoPoolArn:
    Type: String
    Description: ARN of the Cognito Pool
  SenderMail:
    Type: String
    Description: Email of the sender
  ReceiverMail:
    Type: String
    Description: Email of the receiver
  JWTSecret:
    Type: String
    Description: JWT Secret
Resources:
  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${Environment}--ApiGatewayRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName:
          Fn::Sub: ${Environment}--ApiGatewayRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
            - Fn::GetAtt:
              - VMSLoginGET
              - Arn
            - Fn::GetAtt:
              - VMSVisitorGET
              - Arn
            - Fn::GetAtt:
              - VMSVisitorPOST
              - Arn
            - Fn::GetAtt:
              - VMSVisitorIdGET
              - Arn
            - Fn::GetAtt:
              - VMSVisitorIdPUT
              - Arn
            - Fn::GetAtt:
              - VMSVisitGET
              - Arn
            - Fn::GetAtt:
              - VMSVisitPOST
              - Arn
            - Fn::GetAtt:
              - VMSVisitIdGET
              - Arn
            - Fn::GetAtt:
              - VMSVisitIdPATCH
              - Arn
            - Fn::GetAtt:
              - VMSCardGET
              - Arn
            - Fn::GetAtt:
              - VMSCardPOST
              - Arn
            - Fn::GetAtt:
              - VMSCardIdGET
              - Arn
            - Fn::GetAtt:
              - VMSCardIdPUT
              - Arn
            - Fn::GetAtt:
              - VMSApprovalPOST
              - Arn
            - Fn::GetAtt:
              - VMSApprovalIdPATCH
              - Arn
            - Fn::GetAtt:
              - VMSApprovalIdGET
              - Arn
            - Fn::GetAtt:
              - VMSForgotPasswordPOST
              - Arn
    Metadata:
      SamResourceId: ApiGatewayRole
  VMSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: Environment
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://udbhav-code-sam/7df1ea27db0029da34dcd2311fc8cdaf
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: '''*'''
              Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
              Access-Control-Allow-Methods: '''GET,OPTIONS,POST,PUT,DELETE'''
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: '''*'''
              Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
              Access-Control-Allow-Methods: '''GET,OPTIONS,POST,PUT,DELETE'''
    Metadata:
      SamResourceId: VMSApiGateway
  VMSLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-VMS-Layer
      Description: VMS Lambda Layer
      ContentUri: s3://udbhav-code-sam/92a229560ac8089bb1fe0ae6df19511b
      CompatibleRuntimes:
      - python3.11
    Metadata:
      SamResourceId: VMSLayer
  VMSLoginGET:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          UserPoolClientId:
            Ref: UserPoolClientId
          UserPoolId:
            Ref: UserPoolId
      FunctionName:
        Fn::Sub: ${Environment}-VMS-login-GET
      CodeUri: s3://udbhav-code-sam/217795ac7f06c96a78d0d25fc89c8eb3
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSLoginGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /login/{proxy+}
            Method: post
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /login/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSLoginGET
  VMSForgotPasswordPOST:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          UserPoolClientId:
            Ref: UserPoolClientId
          UserPoolId:
            Ref: UserPoolId
      FunctionName:
        Fn::Sub: ${Environment}-VMS-forgot-password-POST
      CodeUri: s3://udbhav-code-sam/2d6f24b986cf76a95a4e42190b7302ae
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSForgotPasswordPOST:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /forgot_password/{proxy+}
            Method: post
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSForgotPasswordPOST
  VMSVisitorGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visitor-GET
      CodeUri: s3://udbhav-code-sam/7a4deecd340a215a5800d60c122f14e5
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSVisitorGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visitor/{proxy+}
            Method: get
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitorGET
  VMSVisitorPOST:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visitor-POST
      CodeUri: s3://udbhav-code-sam/60cc57212b5a1884e064c247b4f331c9
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Role:
        Ref: LambdaIAMRoleArn
      Events:
        VMSVisitorPOST:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visitor/{proxy+}
            Method: post
        Options:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visitor/{proxy+}
            Method: options
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitorPOST
  VMSVisitorIdGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visitor-id-GET
      CodeUri: s3://udbhav-code-sam/5861a0a1ec8f730fc0a565e6a393fab0
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSVisitorVisitorIdGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visitor/{id}/{proxy+}
            Method: get
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitorIdGET
  VMSVisitorIdPUT:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visitor-id-PUT
      CodeUri: s3://udbhav-code-sam/ae2df3e19d574265c837abb57e15d7b9
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSVisitorVisitorIdPUT:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visitor/{id}/{proxy+}
            Method: put
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitorIdPUT
  VMSVisitGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visit-GET
      CodeUri: s3://udbhav-code-sam/5a683b803fcabec1ce13b723e9d3acef
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSVisitGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visit/{proxy+}
            Method: get
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitGET
  VMSVisitPOST:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visit-POST
      CodeUri: s3://udbhav-code-sam/4e3e9c3531b584c6ff23f098b295c1e0
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSVisitPOST:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visit/{proxy+}
            Method: post
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitPOST
  VMSVisitIdGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visit-id-GET
      CodeUri: s3://udbhav-code-sam/80e4258b262bfb33a8431b00e8e63685
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Role:
        Ref: LambdaIAMRoleArn
      Events:
        VMSVisitVisitIdGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visit/{id}/{proxy+}
            Method: get
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitIdGET
  VMSVisitIdPATCH:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-visit-id-PATCH
      CodeUri: s3://udbhav-code-sam/7a4deecd340a215a5800d60c122f14e5
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSVisitVisitIdPATCH:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /visit/{id}/{proxy+}
            Method: patch
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSVisitIdPATCH
  VMSCardGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-card-GET
      CodeUri: s3://udbhav-code-sam/d653de2d9474875bd8750a3eb092fdeb
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSCardGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /card/{proxy+}
            Method: get
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSCardGET
  VMSCardPOST:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-card-POST
      CodeUri: s3://udbhav-code-sam/90df315b256bfbede35181e26079ba51
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSCardPOST:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /card/{proxy+}
            Method: post
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSCardPOST
  VMSCardIdGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-card-id-GET
      CodeUri: s3://udbhav-code-sam/c86dc9bc0e995e9ba4d1b87ecf736108
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSCardCardIdGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /card/{id}/{proxy+}
            Method: get
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSCardIdGET
  VMSCardIdPUT:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-card-id-PUT
      CodeUri: s3://udbhav-code-sam/4f7f32f55930fb9883a59f7ad6afe88b
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSCardCardIdPUT:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /card/{id}/{proxy+}
            Method: put
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSCardIdPUT
  VMSApprovalPOST:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-approval-POST
      CodeUri: s3://udbhav-code-sam/280e7a20f7723147e135e0a5605774ba
      Handler: app.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          SENDER_EMAIL:
            Ref: SenderMail
          RECIPIENT_EMAIL:
            Ref: ReceiverMail
          JWT_SECRET:
            Ref: JWTSecret
      Layers:
      - Ref: VMSLayer
      Events:
        VMSApprovalPOST:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /approval/{proxy+}
            Method: post
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
      Role:
        Ref: LambdaIAMRoleArn
    Metadata:
      SamResourceId: VMSApprovalPOST
  VMSApprovalIdGET:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-approval-id-GET
      CodeUri: s3://udbhav-code-sam/ed533495a935d67a93b7a09c98688c3b
      Handler: app.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          JWT_SECRET:
            Ref: JWTSecret
      Layers:
      - Ref: VMSLayer
      Events:
        VMSApprovalApprovalIdGET:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /approval/{id}/{proxy+}
            Method: get
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSApprovalIdGET
  VMSApprovalIdPATCH:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-VMS-approval-id-PATCH
      CodeUri: s3://udbhav-code-sam/ab7d4e28fb1f5ef457a8e299726e2a7c
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
      - Ref: VMSLayer
      Events:
        VMSApprovalApprovalIdPATCH:
          Type: Api
          Properties:
            RestApiId:
              Ref: VMSApiGateway
            Path: /approval/{id}/{proxy+}
            Method: patch
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
    Metadata:
      SamResourceId: VMSApprovalIdPATCH
Outputs:
  VMSApiEndpoint:
    Description: VMS API Gateway endpoint URL
    Value:
      Fn::Sub: https://${VMSApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
